//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.IHomeService")]
    public interface IHomeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/GetLength", ReplyAction="http://tempuri.org/IHomeService/GetLengthResponse")]
        int GetLength(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/GetLength", ReplyAction="http://tempuri.org/IHomeService/GetLengthResponse")]
        System.Threading.Tasks.Task<int> GetLengthAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/GetStr", ReplyAction="http://tempuri.org/IHomeService/GetStrResponse")]
        string GetStr(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/GetStr", ReplyAction="http://tempuri.org/IHomeService/GetStrResponse")]
        System.Threading.Tasks.Task<string> GetStrAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/Update", ReplyAction="http://tempuri.org/IHomeService/UpdateResponse")]
        System.ServiceModel.Channels.Message Update(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeService/Update", ReplyAction="http://tempuri.org/IHomeService/UpdateResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> UpdateAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHomeServiceChannel : TestDemo.TestService.IHomeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeServiceClient : System.ServiceModel.ClientBase<TestDemo.TestService.IHomeService>, TestDemo.TestService.IHomeService {
        
        public HomeServiceClient() {
        }
        
        public HomeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetLength(string name) {
            return base.Channel.GetLength(name);
        }
        
        public System.Threading.Tasks.Task<int> GetLengthAsync(string name) {
            return base.Channel.GetLengthAsync(name);
        }
        
        public string GetStr(string str) {
            return base.Channel.GetStr(str);
        }
        
        public System.Threading.Tasks.Task<string> GetStrAsync(string str) {
            return base.Channel.GetStrAsync(str);
        }
        
        public System.ServiceModel.Channels.Message Update(System.ServiceModel.Channels.Message request) {
            return base.Channel.Update(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> UpdateAsync(System.ServiceModel.Channels.Message request) {
            return base.Channel.UpdateAsync(request);
        }
    }
}
